on: push
name: Build Docker Image
jobs:
  dockerRegistry:
    name: Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Registry
      run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY_URL --username $DOCKER_USERNAME --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com
    - name: Docker Build
      run: docker build -t 2ndkauboy/docker-letsencrypt .
    - name: Docker Tag
      run: docker tag 2ndkauboy/docker-letsencrypt docker.pkg.github.com/2ndkauboy/docker-letsencrypt/docker-letsencrypt:latest
    - name: Docker Push
      run: docker push docker.pkg.github.com/2ndkauboy/docker-letsencrypt/docker-letsencrypt:latest
