on: push
name: Build Docker Image
jobs:
  dockerRegistry:
    name: Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Registry
      uses: actions/docker/login@fe7ed3ce992160973df86480b83a2f8ed581cd50
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com
    - name: Docker Build
      run: docker build -t 2ndkauboy/docker-letsencrypt .
    - name: Docker Tag
      run: docker tag docker-letsencrypt docker.pkg.github.com/2ndkauboy/docker-letsencrypt:latest
    - name: Docker Push
      run: docker push docker.pkg.github.com/2ndkauboy/docker-letsencrypt:latest
